@baseURL = http://localhost:3333

### Rota de Teste
# Skynet
GET {{baseURL}}

# Rotas de Users
### listOne
GET {{baseURL}}/users/2

### listAll
GET {{baseURL}}/users/?limit=10&offset=0

### create
POST {{baseURL}}/users
Content-Type: application/json

{
	"name": "Migue Ramos",
	"email": "miguel@gmail.com",
	"password": "123456",
	"role": "CLIENTE",
	"active": true,
	"instant": "2026-09-12T13:26:27.957Z"
}

### upadateAll
PUT  {{baseURL}}/users/4
Content-Type: application/json

{
	"name": "Migue Ramos",
	"email": "miguel@gmail.com",
	"password": "123456",
	"role": "ADMIN",
	"active": true,
	"instant": "2026-09-12T13:26:27.957Z"
}

### upadatePartial
PATCH {{baseURL}}/users/1
Content-Type: application/json

{
	"role": "ADMIN"
}

### upadatePartial
DELETE {{baseURL}}/users/1

